## Activity Recognition for Sensor-based Data

### Group Members:
- #### BCSF20M032
- #### BCSF20M042
- #### BCSF20M044

In [1]:
import numpy as np

- #### Reading Training Data

In [2]:
train_Accelerometer = np.load("trainAccelerometer.npy")
train_Gravity = np.load("trainGravity.npy")
train_Gyroscope = np.load("trainGyroscope.npy")
train_JinsAccelerometer = np.load("trainJinsAccelerometer.npy")
train_JinsGyroscope = np.load("trainJinsGyroscope.npy")
train_LinearAcceleration = np.load("trainLinearAcceleration.npy")
train_Magnetometer = np.load("trainMagnetometer.npy")
train_MSAccelerometer = np.load("trainMSAccelerometer.npy")
train_MSGyroscope = np.load("trainMSGyroscope.npy")
train_Labels = np.load("trainLabels.npy")

- #### Reading Testing Data

In [3]:
test_Accelerometer = np.load("testAccelerometer.npy")
test_Gravity = np.load("testGravity.npy")
test_Gyroscope = np.load("testGyroscope.npy")
test_JinsAccelerometer = np.load("testJinsAccelerometer.npy")
test_JinsGyroscope = np.load("testJinsGyroscope.npy")
test_LinearAcceleration = np.load("testLinearAcceleration.npy")
test_Magnetometer = np.load("testMagnetometer.npy")
test_MSAccelerometer = np.load("testMSAccelerometer.npy")
test_MSGyroscope = np.load("testMSGyroscope.npy")
test_Labels = np.load("testLabels.npy")

In [4]:
print(train_Accelerometer.shape)
print(train_Gravity.shape)
print(train_Gyroscope.shape)
print(train_JinsAccelerometer.shape)
print(train_JinsGyroscope.shape)
print(train_LinearAcceleration.shape)
print(train_Magnetometer.shape)
print(train_MSAccelerometer.shape)
print(train_MSGyroscope.shape)
print(train_Labels.shape)

print(test_Accelerometer.shape)
print(test_Gravity.shape)
print(test_Gyroscope.shape)
print(test_JinsAccelerometer.shape)
print(test_JinsGyroscope.shape)
print(test_LinearAcceleration.shape)
print(test_Magnetometer.shape)
print(test_MSAccelerometer.shape)
print(test_MSGyroscope.shape)
print(test_Labels.shape)

(2284, 800, 3)
(2284, 800, 3)
(2284, 800, 3)
(2284, 80, 3)
(2284, 80, 3)
(2284, 800, 3)
(2284, 200, 3)
(2284, 268, 3)
(2284, 268, 3)
(2284,)
(2288, 800, 3)
(2288, 800, 3)
(2288, 800, 3)
(2288, 80, 3)
(2288, 80, 3)
(2288, 800, 3)
(2288, 200, 3)
(2288, 268, 3)
(2288, 268, 3)
(2288,)


In [5]:
# Number of Training and Testing Examples
m_train = np.shape(train_Labels)[0]
m_test = np.shape(test_Labels)[0]
print("Training Examples: ", m_train)
print("Testing Examples: ", m_test)

Training Examples:  2284
Testing Examples:  2288


In [6]:
# 3D array to store features
total_features = 10
train_features = np.zeros((m_train, 9*total_features, 3))
test_features = np.zeros((m_test, 9*total_features, 3))

print(np.shape(train_features))
print(np.shape(test_features))

(2284, 90, 3)
(2288, 90, 3)


In [7]:
from numpy import mean 
from scipy.stats import entropy

- #### Extracting & Learning Meaningful Features

In [8]:
#10 features (mean, median, max, min, sum, range, std, var, percentile 25, percentile 75 )

# For Training DataSet
num_sensors = 9
for i in range(num_sensors):
    sensor = None
    if i == 0:
        sensor = train_Accelerometer
    elif i == 1:
        sensor = train_Gravity
    elif i == 2:
        sensor = train_Gyroscope
    elif i == 3:
        sensor = train_JinsAccelerometer
    elif i == 4:
        sensor = train_JinsGyroscope
    elif i == 5:
        sensor = train_LinearAcceleration
    elif i == 6:
        sensor = train_Magnetometer
    elif i == 7:
        sensor = train_MSAccelerometer
    elif i == 8:
        sensor = train_MSGyroscope

    train_features[:,i * total_features,:] = np.mean(sensor, axis=1)
    train_features[:,i * total_features + 1,:] = np.median(sensor, axis=1)
    train_features[:,i * total_features + 2,:] = np.max(sensor, axis=1)
    train_features[:,i * total_features + 3,:] = np.min(sensor, axis=1)
    train_features[:,i * total_features + 4,:] = np.sum(sensor, axis=1)
    train_features[:,i * total_features + 5,:] = np.max(sensor, axis=1) - np.min(sensor, axis=1)
    train_features[:,i * total_features + 6,:] = np.std(sensor, axis=1)
    train_features[:,i * total_features + 7,:] = np.var(sensor, axis=1)
    train_features[:,i * total_features + 8,:] = np.percentile(sensor, 25, axis=1)
    train_features[:,i * total_features + 9,:] = np.percentile(sensor, 75, axis=1)


In [9]:
# For Testing DataSet, Extracting Features

for i in range(num_sensors):
    sensor = None
    if i == 0:
        sensor = test_Accelerometer
    elif i == 1:
        sensor = test_Gravity
    elif i == 2:
        sensor = test_Gyroscope
    elif i == 3:
        sensor = test_JinsAccelerometer
    elif i == 4:
        sensor = test_JinsGyroscope
    elif i == 5:
        sensor = test_LinearAcceleration
    elif i == 6:
        sensor = test_Magnetometer
    elif i == 7:
        sensor = test_MSAccelerometer
    elif i == 8:
        sensor = test_MSGyroscope

    test_features[:, i * total_features, :] = np.mean(sensor, axis=1)
    test_features[:, i * total_features + 1, :] = np.median(sensor, axis=1)
    test_features[:, i * total_features + 2, :] = np.max(sensor, axis=1)
    test_features[:, i * total_features + 3, :] = np.min(sensor, axis=1)
    test_features[:, i * total_features + 4, :] = np.sum(sensor, axis=1)
    test_features[:, i * total_features + 5, :] = np.max(sensor, axis=1) - np.min(sensor, axis=1)
    test_features[:, i * total_features + 6, :] = np.std(sensor, axis=1)
    test_features[:, i * total_features + 7, :] = np.var(sensor, axis=1)
    test_features[:, i * total_features + 8, :] = np.percentile(sensor, 25, axis=1)
    test_features[:, i * total_features + 9, :] = np.percentile(sensor, 75, axis=1)


In [10]:
# Reshaping to 2D
print(np.shape(train_features))
train_features_reshaped = np.reshape(train_features, (np.shape(train_features)[0], np.shape(train_features)[1]*np.shape(train_features)[2] ))
print(np.shape(train_features_reshaped))

print(np.shape(test_features))
test_features_reshaped = np.reshape(test_features, (np.shape(test_features)[0], np.shape(test_features)[1]*np.shape(test_features)[2] ))
print(np.shape(test_features_reshaped))

(2284, 90, 3)
(2284, 270)
(2288, 90, 3)
(2288, 270)


In [11]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, recall_score

- #### Multi-class Classification using SVM

In [12]:
classfier = SVC(C=1.0, kernel='linear')  
classfier.fit(train_features_reshaped,train_Labels)
predicted_Labels = classfier.predict(test_features_reshaped)

- #### Evaluation Methods

In [15]:
accuracy = accuracy_score(test_Labels,predicted_Labels)
recall = recall_score(test_Labels,predicted_Labels,average='macro')
weightedF1 = f1_score(test_Labels,predicted_Labels,average='weighted')
averageF1 = f1_score(test_Labels,predicted_Labels,average='macro')
conf_matrix = confusion_matrix(test_Labels,predicted_Labels)

print('Average F1-score =' , averageF1)
print('Test Recall =' ,round((recall*100),2))
print('Test accuracy =' , round((accuracy*100),2))
print('Weighted F1-score =', (weightedF1))
print('\nConfusion Matrix:')
print(conf_matrix)



Average F1-score = 0.3936651917217737
Test Recall = 39.6
Test accuracy = 39.47
Weighted F1-score = 0.3935419108319004

Confusion Matrix:
[[20  0  1 ...  0  0  1]
 [ 0 33  2 ...  1  0  0]
 [ 0  7  6 ...  0  0  0]
 ...
 [ 0  0  4 ...  8  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 1  1  1 ...  2  0 14]]
